{
    'name': 'BrainPack Base',
    'version': '16.0.0.2',
    'author': 'BrainPack',
    'website': 'https://www.brainpack.io',
    'license': 'LGPL-3',
    'sequence': 2,
    'images': [],
    'summary': """
    """,
    'depends': [
        'base_setup',
        'web',
        'mail',
        'iap',
        'crm',
        'website',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/app_odoo_customize_views.xml',
        'views/app_theme_config_settings_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings.xml',
        'views/portal_templates.xml',
        'views/crm_lead_view.xml',
        'views/res_users.xml',
        'views/website_templates.xml',
        # 'views/menu.xml',
        'data/ir_config_parameter_data.xml',
        'data/res_company_data.xml',
        'data/res_config_settings.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'brainpack_debranding/static/src/js/app_window_title.js',
            'brainpack_debranding/static/src/js/user_menu.js',
            'brainpack_debranding/static/src/js/dialog.js',
            'brainpack_debranding/static/src/js/error_dialogs.js',
            'brainpack_debranding/static/src/js/block_ui.js',
            'brainpack_debranding/static/src/css/style.css',
            'brainpack_debranding/static/src/xml/settings_page.xml',
            'brainpack_debranding/static/src/xml/error_dialog.xml',
            'brainpack_debranding/static/src/xml/notification_alert.xml',
            'brainpack_debranding/static/src/xml/loading_indicator.xml',
        ],
        'web.assets_frontend': [
            'brainpack_debranding/static/src/css/front_style.css',
            'brainpack_debranding/static/src/js/error_dialogs.js',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'description': """

    """,
}